DROP TABLE tessera CASCADE CONSTRAINTS;

DROP TABLE cliente_reg CASCADE CONSTRAINTS;

DROP TABLE cliente CASCADE CONSTRAINTS;

DROP TABLE videogiochi_rep CASCADE CONSTRAINTS;

DROP TABLE affitta_postazione CASCADE CONSTRAINTS; 

DROP TABLE postazione CASCADE CONSTRAINTS;

DROP TABLE giochi_tavolo_rep CASCADE CONSTRAINTS; 

DROP TABLE affitta_tavolo CASCADE CONSTRAINTS;

DROP TABLE tavolo CASCADE CONSTRAINTS;

DROP TABLE reparto CASCADE CONSTRAINTS;

DROP TABLE filiale CASCADE CONSTRAINTS;

DROP TABLE stipendio CASCADE CONSTRAINTS; 

DROP TABLE amministratore CASCADE CONSTRAINTS;

DROP TABLE direttore CASCADE CONSTRAINTS;

DROP TABLE impiegato CASCADE CONSTRAINTS;

DROP TABLE lavoratore CASCADE CONSTRAINTS;

DROP TABLE casaproduttrice CASCADE CONSTRAINTS;

DROP TABLE prodotto CASCADE CONSTRAINTS;

DROP TABLE vende CASCADE CONSTRAINTS;

DROP TABLE gadget CASCADE CONSTRAINTS;

DROP TABLE periferica CASCADE CONSTRAINTS;

DROP TABLE console CASCADE CONSTRAINTS;

DROP TABLE gioco_tavolo CASCADE CONSTRAINTS;

DROP TABLE videogioco CASCADE CONSTRAINTS;

DROP TABLE fornitore CASCADE CONSTRAINTS;

DROP TABLE fornitura CASCADE CONSTRAINTS;

DROP TABLE prodotti_contenuti CASCADE CONSTRAINTS;

DROP TABLE approvviggionamento CASCADE CONSTRAINTS;

DROP TABLE consiste CASCADE CONSTRAINTS;

DROP TABLE genere CASCADE CONSTRAINTS;

DROP TABLE evento CASCADE CONSTRAINTS;

DROP TABLE torneo CASCADE CONSTRAINTS;

DROP TABLE distribuzione CASCADE CONSTRAINTS;

DROP TABLE partecipa CASCADE CONSTRAINTS;

DROP TABLE gadget_dist CASCADE CONSTRAINTS;

DROP TABLE offerta CASCADE CONSTRAINTS;

DROP TABLE ottiene CASCADE CONSTRAINTS;

DROP TABLE crea CASCADE CONSTRAINTS;

DROP TABLE organizza CASCADE CONSTRAINTS;

DROP TABLE soggetto CASCADE CONSTRAINTS;
